DROP TABLE IF EXISTS products;
CREATE TABLE IF NOT EXISTS products ( id INTEGER PRIMARY KEY AUTOINCREMENT, name VARCHAR(50) UNIQUE, unit VARCHAR(50), expire VARCHAR(20), notes TEXT );
CREATE TRIGGER IF NOT EXISTS products_trig_delete AFTER DELETE ON products FOR EACH ROW BEGIN DELETE FROM batch WHERE prod_id=OLD.id; END;

DROP TABLE IF EXISTS batch;
CREATE TABLE IF NOT EXISTS batch ( id INTEGER PRIMARY KEY AUTOINCREMENT, prod_id INTEGER, spec VARCHAR(50), price VARCHAR(20), unit VARCHAR(50), start_qty FLOAT, booking VARCHAR(20), expire VARCHAR(20), used_qty FLOAT, date VARCHAR(20), notes TEXT, invoice_no VARCHAR(200) );
CREATE TRIGGER IF NOT EXISTS batch_trig_delete AFTER DELETE ON batch FOR EACH ROW BEGIN DELETE FROM distributor WHERE batch_id=OLD.id; END;

DROP TABLE IF EXISTS distributor;
CREATE TABLE IF NOT EXISTS distributor ( id INTEGER PRIMARY KEY AUTOINCREMENT, batch_id INTEGER, quantity FLOAT, distdate VARCHAR(20), registered VARCHAR(20), reason VARCHAR(100), reason2 VARCHAR(100), reason3 INTEGER );

DROP TABLE IF EXISTS meal;
CREATE TABLE IF NOT EXISTS meal ( id INTEGER PRIMARY KEY AUTOINCREMENT, distdate VARCHAR(20), dirty INTEGER, scouts INTEGER, leaders INTEGER, others INTEGER, avcosts FLOAT, notes TEXT );
CREATE TRIGGER IF NOT EXISTS meal_trig_delete AFTER DELETE ON meal FOR EACH ROW BEGIN DELETE FROM distributor WHERE reason3=2 AND reason=OLD.id; END;

DROP TABLE IF EXISTS settings;
CREATE TABLE IF NOT EXISTS settings ( key VARCHAR(32) PRIMARY KEY UNIQUE, value VARCHAR(64) );
INSERT INTO settings VALUES (1, 0);
INSERT INTO settings VALUES (2, "");
INSERT INTO settings VALUES (4, "");
INSERT INTO settings VALUES (8, "");
INSERT INTO settings VALUES (16, 0);
INSERT INTO settings VALUES (32, 0);
INSERT INTO settings VALUES (64, "");
INSERT INTO settings VALUES (128, "");
INSERT INTO settings VALUES (256, "");
